site_name: Uthman Adeleye — DevOps Docs-as-Code
repo_url: https://github.com/Uthmanade001/docs-as-code-portfolio
theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
markdown_extensions:
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Projects:
      - Voting App (Docker → ECR → EC2/EKS): projects/voting-app.md
  - Runbooks:
      - Kubernetes On-Call: runbooks/k8s-oncall.md
      - CI/CD Troubleshooting: runbooks/cicd-troubleshooting.md
  - How-To Guides:
      - GitHub Actions OIDC to AWS: guides/gha-oidc-aws.md
      - Helm Basics: guides/helm-basics.md
  - About: about.md


